import fs from "node:fs";
import path from "node:path";
import { scoreProject } from "./scorecard.js";

export function buildCatalog(rootDir) {
  const toolsDir = path.join(rootDir, "library", "tools");
  const entries = [];
  if (!fs.existsSync(toolsDir)) return { schemaVersion: "gutenberg.catalog.v1", generatedAt: new Date().toISOString(), tools: [] };

  for (const dirent of fs.readdirSync(toolsDir, { withFileTypes: true })) {
    if (!dirent.isDirectory()) continue;
    const projectDir = path.join(toolsDir, dirent.name);
    const manifestPath = path.join(projectDir, "gutenberg.manifest.json");
    if (!fs.existsSync(manifestPath)) continue;
    let manifest = null;
    try {
      manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    } catch {
      continue;
    }
    let scorecard = null;
    try {
      scorecard = scoreProject(projectDir);
    } catch {
      scorecard = null;
    }
    entries.push({
      slug: manifest.slug || dirent.name,
      name: manifest.name || dirent.name,
      projectDir: path.relative(rootDir, projectDir).replaceAll(path.sep, "/"),
      kind: manifest.kind || "tool",
      description: manifest.description || manifest.insights?.thesis || `Generated by Gutenberg.`,
      operations: Array.isArray(manifest.operations) ? manifest.operations.length : (manifest.sources ? manifest.sources.length : 0),
      tags: manifest.tags || [],
      heroes: Array.isArray(manifest.heroes) ? manifest.heroes.slice(0, 20) : [],
      score: scorecard ? Math.round((scorecard.ratio || 0) * 100) : null,
      grade: scorecard?.grade || null,
      ratio: scorecard?.ratio ?? null,
      badges: scorecard?.badges || [],
      verified: Boolean(manifest.verification?.ok),
      proofFile: manifest.verification?.proofFile || null,
      dimensions: scorecard?.dimensions || null,
      provenance: manifest.provenance ? {
        generatedAt: manifest.provenance.generatedAt,
        gutenbergVersion: manifest.provenance.gutenbergVersion,
        specSha: manifest.provenance.spec?.sha256?.slice(0, 12) || null,
        targets: manifest.provenance.targets || []
      } : null
    });
  }

  entries.sort((a, b) => (b.score ?? -1) - (a.score ?? -1));

  return {
    schemaVersion: "gutenberg.catalog.v1",
    generatedAt: new Date().toISOString(),
    rootDir,
    tools: entries
  };
}

export function writeCatalogDataFile(catalog, outFile) {
  const js = `// Generated by 'gutenberg site build' — do not edit by hand.\nwindow.__GUTENBERG_REGISTRY__ = ${JSON.stringify(catalog, null, 2)};\n`;
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, js, "utf8");
}

export function buildRegistryFromCatalog(rootDir) {
  const catalog = buildCatalog(rootDir);
  return {
    schemaVersion: "gutenberg.registry.v1",
    generatedAt: catalog.generatedAt,
    source: "library/tools/*/gutenberg.manifest.json",
    tools: catalog.tools.map((tool) => ({
      slug: tool.slug,
      name: tool.name,
      kind: tool.kind,
      package: tool.projectDir || `library/tools/${tool.slug}`,
      status: registryStatus(tool),
      description: tool.description,
      categories: registryCategories(tool),
      operations: tool.operations,
      heroes: Array.isArray(tool.heroes) ? tool.heroes.length : 0,
      score: tool.score,
      grade: tool.grade,
      badges: tool.badges || [],
      verified: Boolean(tool.verified),
      proofFile: tool.proofFile || null,
      authRequired: authRequired(tool),
      entrypoints: {
        manifest: `${tool.projectDir || `library/tools/${tool.slug}`}/gutenberg.manifest.json`,
        cli: tool.kind === "aggregator"
          ? `${tool.projectDir || `library/tools/${tool.slug}`}/cmd/${tool.slug}`
          : `${tool.projectDir || `library/tools/${tool.slug}`}/cmd/${tool.slug}`,
        mcp: tool.kind === "aggregator" ? null : `${tool.slug} mcp`,
        install: `gutenberg install ${tool.projectDir || `library/tools/${tool.slug}`}`
      }
    }))
  };
}

export function writeRegistryFile(registry, outFile) {
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, `${JSON.stringify(registry, null, 2)}\n`, "utf8");
}

function registryStatus(tool) {
  if (tool.verified || (tool.score ?? 0) >= 90) return "verified";
  if ((tool.score ?? 0) >= 60) return "prototype";
  return "prototype";
}

function registryCategories(tool) {
  const categories = new Set();
  if (tool.kind) categories.add(tool.kind);
  for (const tag of tool.tags || []) categories.add(String(tag).toLowerCase());
  for (const badge of tool.badges || []) categories.add(String(badge).toLowerCase().replace(/\s+/g, "-"));
  return [...categories].slice(0, 12);
}

function authRequired(tool) {
  const dimensions = tool.dimensions || {};
  const auth = dimensions.auth;
  if (!auth) return null;
  return auth.score < auth.max;
}
