import path from "node:path";
import { writeText } from "./fs.js";

export function generateClaudeSkill(manifest, outDir) {
  const skillDir = path.join(outDir, "skills", manifest.slug);
  writeText(path.join(skillDir, "SKILL.md"), skillMarkdown(manifest));
  return { skillDir, file: path.join(skillDir, "SKILL.md") };
}

function skillMarkdown(manifest) {
  if (manifest.kind === "aggregator") return aggregatorSkillMarkdown(manifest);
  const operations = Array.isArray(manifest.operations) ? manifest.operations : [];
  const reads = operations.filter((op) => op.risk === "read");
  const writes = operations.filter((op) => op.risk !== "read");
  const exampleRead = reads[0] || operations[0];
  const exampleWrite = writes[0];
  const sources = Array.isArray(manifest.sources) ? manifest.sources : [];
  const baseUrl = manifest.baseUrls?.[0] || sources[0]?.baseUrls?.[0] || "https://api.example.com";

  const description = `${manifest.insights?.thesis || manifest.description || `Agent-native CLI for ${manifest.name}.`} Use for ${operations.length || sources.length} operation/source entries against ${baseUrl}.`.trim();

  return `---
name: ${manifest.slug}
description: ${escapeFrontmatter(description)}
---

# ${manifest.name}

Generated by Gutenberg. Use this skill to call the ${manifest.name} API through the local \`${manifest.slug}\` CLI.

## When to use

- The user asks for data exposed by ${manifest.name} (${listTags(manifest.tags)}).
- An agent task needs structured JSON from ${baseUrl}.
- You need to perform a write/destructive operation on ${manifest.name} — always preview first, run with \`--yes\` only on explicit user confirmation.

## How to invoke

The skill assumes the generated CLI is on PATH (or invoke via \`scripts/use-go.sh run ./cmd/${manifest.slug}\` from the project directory).

\`\`\`bash
${manifest.slug} operations
${manifest.slug} call ${exampleRead?.id || "operationId"} --json
${manifest.slug} sync --json
${manifest.slug} search "<keyword>" --json
\`\`\`

${exampleWrite ? `Preview a write operation (default behavior, no side effects):

\`\`\`bash
${manifest.slug} call ${exampleWrite.id} --data '{"example":true}' --json
\`\`\`

Execute it (only after explicit user confirmation):

\`\`\`bash
${manifest.slug} call ${exampleWrite.id} --data '{"example":true}' --yes --json
\`\`\`
` : ""}
## Authentication

${authSection(manifest)}

## Operations index

${operations.length > 0 ? operations
  .slice(0, 50)
  .map((op) => `- \`${op.id}\` (${op.method} ${op.path}) — ${op.risk}${op.summary ? ` — ${op.summary}` : ""}`)
  .join("\n") : sources.map((source) => `- \`${source.slug}\` — operation: ${source.operation || "n/a"}${source.displayName ? ` — ${source.displayName}` : ""}`).join("\n")}
${operations.length > 50 ? `\n…and ${operations.length - 50} more. Run \`${manifest.slug} operations --json\` for the full list.\n` : ""}

## Output contract

- All commands accept \`--json\` and emit machine-readable output.
- \`call\` returns \`{ dryRun, operation, request, response }\`. \`dryRun: true\` means the call was not executed (write op without \`--yes\`).
- \`search\` returns cached records. \`sync\` populates the local SQLite cache.

## Provenance

- Schema: ${manifest.schemaVersion}
- Generated by: ${manifest.generatedBy} ${manifest.generatedByVersion || ""}
- Source spec: ${manifest.source || "n/a"}
`;
}

function aggregatorSkillMarkdown(manifest) {
  const sources = Array.isArray(manifest.sources) ? manifest.sources : [];
  const description = `${manifest.description || `Agent-native aggregator for ${manifest.name}.`} Use for fan-out workflows across ${sources.length} source tools.`;
  const firstSource = sources[0];

  return `---
name: ${manifest.slug}
description: ${escapeFrontmatter(description)}
---

# ${manifest.name}

Generated by Gutenberg. Use this skill to run the local \`${manifest.slug}\` aggregator CLI across multiple API sources and return one merged JSON result.

## When to use

- The user asks for a cross-source view covered by ${sources.map((source) => source.displayName || source.slug).join(", ") || "the configured sources"}.
- An agent task needs one command that fans out to multiple APIs and ranks or merges the results.

## How to invoke

\`\`\`bash
${manifest.slug} sources
${manifest.slug} fan-out --json
${manifest.slug} fan-out --param key=value --json
\`\`\`

## Sources

${sources.map((source) => `- \`${source.slug}\` — ${source.displayName || source.slug}; operation: ${source.operation || "n/a"}; base: ${(source.baseUrls || [])[0] || "n/a"}`).join("\n")}

## Output contract

- \`sources\` lists the embedded source manifests.
- \`fan-out --json\` returns merged/ranked items from each source.
- Source-specific credentials use each source env prefix, not the aggregator prefix.

## Provenance

- Schema: ${manifest.schemaVersion}
- Merge strategy: ${manifest.merge || "n/a"}
- Rank strategy: ${manifest.rank || "n/a"}
- Example source: ${firstSource ? `${firstSource.slug} ${firstSource.operation || ""}`.trim() : "n/a"}
`;
}

function authSection(manifest) {
  const mode = manifest.auth?.mode || "none";
  const env = manifest.envPrefix;
  if (mode === "none") {
    return `No authentication required.`;
  }
  if (mode === "oauth") {
    return `OAuth required. Configure with:

\`\`\`bash
${manifest.slug} auth status
${manifest.slug} auth config
${manifest.slug} auth client-credentials --token-url URL --client-id ID --client-secret SECRET
${manifest.slug} auth device --device-url URL --token-url URL --client-id ID
\`\`\`

Tokens are stored in \`${env}_TOKEN_FILE\` (default ~/.gutenberg/${manifest.slug}-token.json).`;
  }
  return `Set ${env}_API_KEY in the environment, or pass \`--api-key <key>\`.`;
}

function listTags(tags) {
  if (!tags || tags.length === 0) return "general API operations";
  return tags.slice(0, 6).join(", ");
}

function escapeFrontmatter(value) {
  return String(value).replace(/\n+/g, " ").replace(/"/g, '\\"').slice(0, 240);
}
